use std::fmt::Write;

use crate::config::{BuildMode, CompileConfig};
use crate::ir::{OpcodeRegistry, ProgramBlob};
use crate::obfuscation::anti_tamper::RuntimeIntegrity;
use crate::obfuscation::identifier_mangler::IdentifierMangler;
use crate::serializer::EncoderKey;
use crate::vmgen::dispatcher_template::emit_dispatcher;
use crate::vmgen::luau_runtime_template::emit_runtime_support;
use crate::vmgen::opcode_handler_template::emit_opcode_constants;

pub fn emit_luau_output(
    program: &ProgramBlob,
    encoded_blob: &str,
    key: &EncoderKey,
    config: &CompileConfig,
    registry: &OpcodeRegistry,
    integrity: &RuntimeIntegrity,
) -> String {
    let readable = matches!(config.mode, BuildMode::Debug);
    let mut mangler = IdentifierMangler::new(config.seed);
    let encoded_name = if readable {
        "encodedBlob".to_string()
    } else {
        mangler.next_ident()
    };
    let key_name = if readable {
        "runtimeKey".to_string()
    } else {
        mangler.next_ident()
    };
    let cfg_name = if readable {
        "runtimeCfg".to_string()
    } else {
        mangler.next_ident()
    };
    let program_name = if readable {
        "program".to_string()
    } else {
        mangler.next_ident()
    };
    let output_name = if readable {
        "bootstrap".to_string()
    } else {
        mangler.next_ident()
    };

    let mut out = String::new();
    let _ = writeln!(out, "-- generated by BarredLuau");
    let _ = writeln!(out, "local {encoded_name} = \"{encoded_blob}\"");
    let _ = writeln!(
        out,
        "local {key_name} = {{ seed = {}, nonce = {} }}",
        key.seed, key.nonce
    );
    let _ = writeln!(
        out,
        "local {cfg_name} = {{ rounds = {}, alphabet = \"{}\", chunkSize = {}, includeChecksum = {}, interleave = {} }}",
        config.encoder.rounds,
        config.encoder.alphabet,
        config.encoder.chunk_size,
        if config.encoder.include_checksum {
            "true"
        } else {
            "false"
        },
        if config.encoder.interleave {
            "true"
        } else {
            "false"
        }
    );
    out.push_str(&emit_opcode_constants(registry));
    out.push_str(emit_runtime_support());
    out.push_str(emit_dispatcher());
    let _ = writeln!(out, "local function {output_name}()");
    let _ = writeln!(
        out,
        "    local decoded = decodePayload({encoded_name}, {key_name}, {cfg_name})"
    );
    let _ = writeln!(
        out,
        "    local {program_name} = deserializeProgram(decoded)"
    );
    if config.anti_tamper.enabled {
        let _ = writeln!(
            out,
            "    if {program_name}.magic ~= \"BRLU\" or {program_name}.version ~= {} then error(\"barredluau integrity check failed\") end",
            program.version
        );
        if integrity.verify_opcode_table {
            let _ = writeln!(
                out,
                "    if {} ~= {} then error(\"barredluau integrity check failed\") end",
                registry.checksum(),
                integrity.opcode_checksum
            );
        }
    }
    let _ = writeln!(
        out,
        "    return executeProto({program_name}.prototypes[{program_name}.entry + 1], {program_name}.prototypes, _G, {{}}, {{}}, {{}})"
    );
    let _ = writeln!(out, "end");
    let _ = writeln!(out, "return {output_name}()");
    out
}
