use std::fmt::Write;

use crate::config::{BuildMode, CompileConfig};
use crate::ir::{OpcodeRegistry, ProgramBlob};
use crate::obfuscation::anti_tamper::RuntimeIntegrity;
use crate::obfuscation::identifier_mangler::IdentifierMangler;
use crate::obfuscation::literal_encoder::{emit_luau_encoded_string_expr, emit_luau_xor_decoder};
use crate::serializer::EncoderKey;
use crate::vmgen::dispatcher_template::emit_dispatcher;
use crate::vmgen::luau_runtime_template::emit_runtime_support;
use crate::vmgen::opcode_handler_template::emit_opcode_constants;

pub fn emit_luau_output(
    program: &ProgramBlob,
    encoded_blob: &str,
    key: &EncoderKey,
    config: &CompileConfig,
    registry: &OpcodeRegistry,
    integrity: &RuntimeIntegrity,
) -> String {
    let readable = matches!(config.mode, BuildMode::Debug);
    let mut mangler = IdentifierMangler::new(config.seed);
    let string_decoder_name = if readable {
        "decodeRuntimeString".to_string()
    } else {
        mangler.next_ident()
    };
    let encoded_name = if readable {
        "encodedBlob".to_string()
    } else {
        mangler.next_ident()
    };
    let key_name = if readable {
        "runtimeKey".to_string()
    } else {
        mangler.next_ident()
    };
    let cfg_name = if readable {
        "runtimeCfg".to_string()
    } else {
        mangler.next_ident()
    };
    let program_name = if readable {
        "program".to_string()
    } else {
        mangler.next_ident()
    };
    let output_name = if readable {
        "bootstrap".to_string()
    } else {
        mangler.next_ident()
    };
    let runtime_string_key = config.seed.wrapping_mul(31).wrapping_add(17) as u8;
    let alphabet_expr = if readable {
        format!("\"{}\"", config.encoder.alphabet)
    } else {
        emit_luau_encoded_string_expr(
            &config.encoder.alphabet,
            runtime_string_key,
            &string_decoder_name,
        )
    };
    let magic_expr = if readable {
        "\"BRLU\"".to_string()
    } else {
        emit_luau_encoded_string_expr("BRLU", runtime_string_key, &string_decoder_name)
    };
    let integrity_error_expr = if readable {
        "\"barredluau integrity check failed\"".to_string()
    } else {
        emit_luau_encoded_string_expr(
            "barredluau integrity check failed",
            runtime_string_key,
            &string_decoder_name,
        )
    };
    let runtime_fault_expr = if readable {
        "\"barredluau runtime fault\"".to_string()
    } else {
        emit_luau_encoded_string_expr(
            "barredluau runtime fault",
            runtime_string_key,
            &string_decoder_name,
        )
    };
    let colon_expr = if readable {
        "\":\"".to_string()
    } else {
        emit_luau_encoded_string_expr(":", runtime_string_key, &string_decoder_name)
    };
    let unpack_i4_expr = if readable {
        "\"<i4\"".to_string()
    } else {
        emit_luau_encoded_string_expr("<i4", runtime_string_key, &string_decoder_name)
    };
    let unpack_d_expr = if readable {
        "\"<d\"".to_string()
    } else {
        emit_luau_encoded_string_expr("<d", runtime_string_key, &string_decoder_name)
    };

    let mut out = String::new();
    if readable {
        let _ = writeln!(out, "-- generated by BarredLuau");
    } else {
        out.push_str(&emit_luau_xor_decoder(&string_decoder_name));
    }
    let _ = writeln!(out, "local {encoded_name} = \"{encoded_blob}\"");
    let _ = writeln!(
        out,
        "local {key_name} = {{ seed = {}, nonce = {} }}",
        key.seed, key.nonce
    );
    let _ = writeln!(
        out,
        "local {cfg_name} = {{ rounds = {}, alphabet = {}, chunkSize = {}, includeChecksum = {}, interleave = {} }}",
        config.encoder.rounds,
        alphabet_expr,
        config.encoder.chunk_size,
        if config.encoder.include_checksum {
            "true"
        } else {
            "false"
        },
        if config.encoder.interleave {
            "true"
        } else {
            "false"
        }
    );
    out.push_str(&emit_opcode_constants(registry));
    out.push_str(emit_runtime_support());
    out.push_str(emit_dispatcher());
    let _ = writeln!(out, "local function {output_name}()");
    let _ = writeln!(
        out,
        "    local decoded = decodePayload({encoded_name}, {key_name}, {cfg_name})"
    );
    let _ = writeln!(
        out,
        "    local {program_name} = deserializeProgram(decoded)"
    );
    if config.anti_tamper.enabled {
        let _ = writeln!(
            out,
            "    if {program_name}.magic ~= {magic_expr} or {program_name}.version ~= {} then error({integrity_error_expr}) end",
            program.version,
        );
        if integrity.verify_opcode_table {
            let _ = writeln!(
                out,
                "    if {} ~= {} then error({integrity_error_expr}) end",
                registry.checksum(),
                integrity.opcode_checksum
            );
        }
    }
    let _ = writeln!(
        out,
        "    return executeProto({program_name}.prototypes[{program_name}.entry + 1], {program_name}.prototypes, _G, {{}}, {{}}, {{}})"
    );
    let _ = writeln!(out, "end");
    let _ = writeln!(out, "return {output_name}()");

    if readable {
        out
    } else {
        let obfuscated = obfuscate_bootstrap_identifiers(&out, &mut mangler);
        let obfuscated = obfuscated.replace(
            "\"barredluau integrity check failed\"",
            &integrity_error_expr,
        );
        let obfuscated = obfuscated.replace("\"barredluau runtime fault\"", &runtime_fault_expr);
        let obfuscated = obfuscated.replace("\"BRLU\"", &magic_expr);
        let obfuscated = obfuscated.replace("\":\"", &colon_expr);
        let obfuscated = obfuscated.replace("\"<i4\"", &unpack_i4_expr);
        let obfuscated = obfuscated.replace("\"<d\"", &unpack_d_expr);
        minify_luau(&obfuscated)
    }
}

fn obfuscate_bootstrap_identifiers(source: &str, mangler: &mut IdentifierMangler) -> String {
    let identifiers = [
        "OPCODES",
        "LoadNil",
        "LoadBool",
        "LoadNumber",
        "LoadString",
        "Move",
        "GetGlobal",
        "SetGlobal",
        "GetTable",
        "SetTable",
        "NewTable",
        "Call",
        "Return",
        "Jump",
        "JumpIf",
        "JumpIfNot",
        "Closure",
        "GetUpvalue",
        "SetUpvalue",
        "Concat",
        "Add",
        "Sub",
        "Mul",
        "Div",
        "Mod",
        "Pow",
        "Eq",
        "Lt",
        "Le",
        "Len",
        "Not",
        "fnv32",
        "newPrng",
        "buildPermutation",
        "invertPermutation",
        "streamTransform",
        "buildSubstitution",
        "invertSubstitution",
        "substitute",
        "decodeText",
        "deinterleave",
        "bytesToString",
        "decodePayload",
        "deserializeProgram",
        "readOperand",
        "writeRegister",
        "captureClosure",
        "executeProto",
        "state",
        "nextU32",
        "nextByte",
        "bounded",
        "length",
        "seed",
        "nonce",
        "rounds",
        "alphabet",
        "chunkSize",
        "includeChecksum",
        "interleave",
        "permutation",
        "prng",
        "target",
        "tmp",
        "restored",
        "substitution",
        "inverse",
        "text",
        "reverse",
        "digits",
        "radix",
        "leftSize",
        "parts",
        "offset",
        "chunk",
        "upper",
        "payload",
        "round",
        "roundSeed",
        "start",
        "checksum",
        "data",
        "blob",
        "cursor",
        "readByte",
        "readU16",
        "readU32",
        "readVarU32",
        "readString",
        "magic",
        "version",
        "featureFlags",
        "entry",
        "protoCount",
        "prototypes",
        "protoIndex",
        "hasName",
        "name",
        "paramCount",
        "params",
        "maxRegisters",
        "returnArity",
        "upvalueCount",
        "upvalues",
        "childCount",
        "children",
        "localNameCount",
        "localNames",
        "constantCount",
        "constants",
        "instructionCount",
        "instructions",
        "tag",
        "value",
        "nextCursor",
        "frame",
        "registerIndex",
        "captured",
        "upvalueMap",
        "proto",
        "env",
        "args",
        "index",
        "outputIndex",
        "argIndex",
        "base",
        "callee",
        "argsBuffer",
        "count",
        "resultIndex",
        "child",
        "tbl",
        "key",
        "results",
        "rhs",
        "decoded",
        "hash",
        "a",
        "b",
        "c",
        "d",
        "o",
    ];

    let mut map = std::collections::BTreeMap::new();
    for identifier in identifiers {
        map.insert(identifier, mangler.next_ident());
    }
    replace_identifiers(source, &map)
}

fn replace_identifiers(
    source: &str,
    replacements: &std::collections::BTreeMap<&str, String>,
) -> String {
    let mut out = String::with_capacity(source.len());
    let chars: Vec<char> = source.chars().collect();
    let mut index = 0usize;
    let mut quote: Option<char> = None;
    while index < chars.len() {
        let ch = chars[index];
        if let Some(delimiter) = quote {
            out.push(ch);
            if ch == '\\' {
                index += 1;
                if index < chars.len() {
                    out.push(chars[index]);
                }
            } else if ch == delimiter {
                quote = None;
            }
            index += 1;
            continue;
        }

        if ch == '\'' || ch == '"' {
            quote = Some(ch);
            out.push(ch);
            index += 1;
            continue;
        }

        if is_ident_start(ch) {
            let start = index;
            index += 1;
            while index < chars.len() && is_ident_continue(chars[index]) {
                index += 1;
            }
            let ident: String = chars[start..index].iter().collect();
            if let Some(replacement) = replacements.get(ident.as_str()) {
                out.push_str(replacement);
            } else {
                out.push_str(&ident);
            }
            continue;
        }

        out.push(ch);
        index += 1;
    }
    out
}

fn minify_luau(source: &str) -> String {
    let mut out = String::with_capacity(source.len());
    let chars: Vec<char> = source.chars().collect();
    let mut index = 0usize;
    let mut quote: Option<char> = None;
    let mut pending_space = false;

    while index < chars.len() {
        let ch = chars[index];
        if let Some(delimiter) = quote {
            out.push(ch);
            if ch == '\\' {
                index += 1;
                if index < chars.len() {
                    out.push(chars[index]);
                }
            } else if ch == delimiter {
                quote = None;
            }
            index += 1;
            continue;
        }

        if ch == '\'' || ch == '"' {
            if pending_space && needs_space(out.chars().last(), Some(ch)) {
                out.push(' ');
            }
            pending_space = false;
            quote = Some(ch);
            out.push(ch);
            index += 1;
            continue;
        }

        if ch == '-' && chars.get(index + 1) == Some(&'-') {
            index += 2;
            while index < chars.len() && chars[index] != '\n' {
                index += 1;
            }
            pending_space = true;
            continue;
        }

        if ch.is_whitespace() {
            pending_space = true;
            index += 1;
            continue;
        }

        if pending_space && needs_space(out.chars().last(), Some(ch)) {
            out.push(' ');
        }
        pending_space = false;
        out.push(ch);
        index += 1;
    }

    out
}

fn needs_space(prev: Option<char>, next: Option<char>) -> bool {
    match (prev, next) {
        (Some(prev), Some(next))
            if is_token_char(prev) && (is_token_char(next) || is_quote(next)) =>
        {
            true
        }
        (Some(prev), Some(next)) if is_quote(prev) && is_token_char(next) => true,
        _ => false,
    }
}

fn is_token_char(ch: char) -> bool {
    ch.is_ascii_alphanumeric() || ch == '_'
}

fn is_quote(ch: char) -> bool {
    ch == '\'' || ch == '"'
}

fn is_ident_start(ch: char) -> bool {
    ch.is_ascii_alphabetic() || ch == '_'
}

fn is_ident_continue(ch: char) -> bool {
    ch.is_ascii_alphanumeric() || ch == '_'
}
